name: climahoje
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_design_icons_flutter: ^4.0.5245
  flutter_mobx: ^1.1.0
  provider: ^4.1.2
  dio: ^3.0.9
  dio_http_cache: ^0.2.5




  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.5
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
